### ISSUE TITLE
encountered a declaration exception: Missing second argument

### ISSUE THREAD

**Issue by Leko** [skovhus/jest-codemods#133]
- jest-codemods: 0.16.0
- Using: Mocha + no assetion library (use built-in `assert` module)
- Jest: 23.6.0

Hi,
An unexpected transform about pending tests.

```
 FAIL  __tests__/spec/xxx.js
  ● xxx › encountered a declaration exception

    Missing second argument. It must be a callback function.

      1 | // @flow
      2 | describe('xxx', () => {
    > 3 |   test('pending it')
        |        ^
      4 | })
      5 |

      at Env.it (../../node_modules/jest-jasmine2/build/jasmine/Env.js:431:15)
      at Suite.<anonymous> (__tests__/spec/xxx.js:3:8)
      at Object.<anonymous> (__tests__/spec/xxx.js:2:1)
```

---

I think this test is incorrect:

https://github.com/skovhus/jest-codemods/blob/ce287998b38df5c52eb6a2239a74afab5e5e3a4d/src/transformers/mocha.test.js#L115-L131

It should be one of these solutions.

1. Add `.skip` and empty function
1. Rename to `xit` and add empty function
1. Rename to `xtest` and add empty function

```js
// @flow
describe.skip('skip suite', () => {
  test.skip('skip test', () => {});
  test.skip('test will be skipped', () => {}); // <--- Add .skip and empty function
});
```

It is correct?

**Comment by Leko** [comment]
@skovhus I just created a pull request for fixing this issue.
https://github.com/skovhus/jest-codemods/pull/134
