### ISSUE TITLE
[TypeScript] Type assertion syntax with angle brackets is handled as JSX, which results in an error

### ISSUE THREAD

**Issue by kimamula** [skovhus/jest-codemods#151]
File examined:

```ts
function doSomething(arg: any) {
  return arg;
}

describe('doSomething', () => {
  it('should do something', () => {
    expect(doSomething(<string>'foo')).toBe('foo');
  });
});
```

Command:

```sh
$ jest-codemods spec.ts 
? Which parser do you want to use? TypeScript
? Which test library would you like to migrate from? Jasmine: globals
? Are you using the global object for assertions (i.e. without requiring them) Yes, and I'm not afraid of false positive transformations
? Will you be using Jest on Node.js as your test runner? Yes, use the globals provided by Jest (recommended)
```

Result:

```sh
ERR spec.ts Transformation error (Unterminated JSX contents (7:31))
```

**Comment by skovhus** [comment]
Thanks! This is an underlying issue with jscodeshift and the Babylon parser we are using. 

It might help if we didn’t default to the tsx parser for all ts(x) files. See https://github.com/skovhus/jest-codemods/blob/master/src/cli/transformers.js

But it does complicate the codebase as we need two transformation runs for TypeScript files then: one for .ts files and one for .tsx. 

🤔

**Comment by alexpearce92** [comment]
Any workaround here? I'm running into the same issue
```bash
$ jest-codemods -d ./path/myTest.spec.ts
? Which parser do you want to use? TypeScript
? Which test library would you like to migrate from? Jasmine: globals
? Are you using the global object for assertions (i.e. without requiring them) No, I use import/require statements for my current assertion library
? Will you be using Jest on Node.js as your test runner? Yes, use the globals provided by Jest (recommended)
Executing command: jscodeshift -t C:\...\node_modules\jest-codemods\dist\transformers\jasmine-globals.js ./path/myTest.spec.ts --dry --ignore-pattern node_modules --parser tsx --extensions=tsx,ts
```

myTest.spec.ts
```typescript
import { EMPTY, of as observableOf, Observable } from 'rxjs';
import { inject, TestBed } from "@angular/core/testing";
import { Store } from "@ngrx/store";

...

class MockStore {
    private requests: AccessRequest[] | string;

    select<T>(key: string): Observable<{}> {
        ...
    }

    dispatch(action: AccessRequestsActions): void {
        this.requests = action.payload; // babel throws error here
    }
}

describe('Access request Service Tests', () => {
    it('should pass', inject([...], (...) => {
        ...
    }));
});

```

Error
```
 ERR ./services/accessrequest.service.spec.ts Transformation error (Unexpected token, expected "}" (22:38))
SyntaxError: Unexpected token, expected "}" (22:38)
    at _class.raise (C:\...\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:4051:15)
    at _class.unexpected (C:\...\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:5382:16)
    at _class.expect (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:5370:28)
    at _class.jsxParseExpressionContainer (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:3606:12)
    at _class.jsxParseElementAt (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:3693:36)
    at _class.jsxParseElement (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:3735:19)
    at _class.parseExprAtom (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:3742:21)
    at _class.parseExprSubscripts (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:6104:21)
    at _class.parseMaybeUnary (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:6083:21)
    at _class.parseMaybeUnary (C:\...\AppData\Roaming\npm\node_modules\jest-codemods\node_modules\@babel\parser\lib\index.js:10675:54)
```

package.json [abridged]
```json
 "dependencies": {
    "@angular/core": "^6.1.3",
    "rxjs": "^6.2.2",
  },
  "devDependencies": {
    "@types/jasmine": "^2.8.12",
    "@types/jest": "^23.0.0",
    "jasmine-core": "2.99.1",
    "jest": "^23.6.0",
    "jest-codemods": "^0.19.1",
    "jest-preset-angular": "6.0.1",
    "typescript": "^2.9.2",
  }
```

**Comment by alexpearce92** [comment]
Made some progress here. It looks like `jest-codemods` blows up when a typescript file is casting an object using the `<GtLt>` syntax, and works fine when swapping it out for the `as` syntax (this was not included in my example above, unfortunately).

I also found a third party implementation that did a bunch of other conversions that `jest-codemods` appears to miss. For anyone interested, check out the conversion file that team posted here: https://gist.github.com/apiv/02b0b5b70bd752304bc8c7e940a5ea29

**Comment by robertkraig** [comment]
@alexpearce92 had the same issue on my end. I think they need to test the file extension to see if it ends with ts, if it does not to parse as JSX.

**Comment by grreeenn** [comment]
Hi, I've stumbled upon this thread while looking for TS type assertions; maybe this cite from docs would help (note the last sentence):
> Type assertions have two forms. One is the “angle-bracket” syntax:
> 
> ```
> let someValue: any = "this is a string";
> 
> let strLength: number = (<string>someValue).length;
> ```
> And the other is the as-syntax:
> 
> ```
> let someValue: any = "this is a string";
> 
> let strLength: number = (someValue as string).length;
> ```
> The two samples are equivalent. Using one over the other is mostly a choice of preference; **however, when using TypeScript with JSX, only as-style assertions are allowed.**

Sorry if it doesn't make sense in this case

**Comment by skovhus** [comment]
Thanks!

For simplicitet we went for using the jsx parser for all typescript files. We need to change that, but it does complicate things (example: we need to expand file globs)

**Comment by biltongza** [comment]
Is there any progress/workaround for this?
