### ISSUE TITLE
Cannot find module 'core-js/modules/**'

### ISSUE THREAD

**Issue by DaniGTA** [skovhus/jest-codemods#187]
### Environment

1. `node -v`: 12.7.0
1. `npm -v`: 6.10.2
1. Operating system: Windows

### Prerequisite
entered:
`npx jest-codemods ./test/**/*.ts`
### Steps to Reproduce

If needed i can invite to the repo

### Expected Behavior

no error

### Actual Behavior

```
Error: Cannot find module 'core-js/modules/es.array.concat'
Require stack:
- C:\Users\<username>\AppData\Roaming\npm-cache\_npx\3860\node_modules\jest-codemods\dist\transformers\jasmine-this.js
- C:\Users\<username>\AppData\Roaming\npm-cache\_npx\3860\node_modules\jest-codemods\node_modules\jscodeshift\src\Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\3860\node_modules\jest-codemods\dist\transformers\jasmine-this.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._compile (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\3860\node_modules\jest-codemods\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.newLoader [as .js] (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\3860\node_modules\jest-codemods\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\<username>\\AppData\\Roaming\\npm-cache\\_npx\\3860\\node_modules\\jest-codemods\\dist\\transformers\\jasmine-this.js',
    'C:\\Users\\<username>\\AppData\\Roaming\\npm-cache\\_npx\\3860\\node_modules\\jest-codemods\\node_modules\\jscodeshift\\src\\Worker.js'
  ]
}
```

**Comment by skovhus** [comment]
That is a weird error. For some reason core-js is missing. Can I get you to install Jest-Codemods using `npm install jest-codemods` in an empty folder? Then you can run it by doing `npm run jest-Codemods` from that folder.

**Comment by DaniGTA** [comment]
on:
`npm install jest-codemods`
`npm run jest-codemods`
i get:

```
npm run jest-codemods
npm ERR! missing script: jest-codemods
```

![image](https://user-images.githubusercontent.com/20490672/71202827-34d7f700-229d-11ea-867e-f324d4697fb5.png)

on:
`npm install jest-codemods -g`
i get:
`npm run jest-codemods` => same error

> (Console restart)

`jest-codemods` => this runs but has same core-js error.

**Comment by skovhus** [comment]
It might be me using yarn for too long. It seems npm run would not run your local installation. https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules

Last test, can you try running `npx jest-codemods` in the folder next to the `node-modules` (the folder you ran npm install in). 

Thanks for helping me debug. And sorry for the inconvenience.

**Comment by DaniGTA** [comment]
That works, thanks ^^.

I startet `npx jest-codemods` on the same folder that used at the first time (That was a folder next to the node-modules). But i restarted my pc between and now it just works 👍
