### ISSUE TITLE
Should Syntax Parsing Error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by yvele** [skovhus/jest-codemods#47]
First of all, than you sooooo much for the Should Syntax implementation 😁 

I'm using jest-codemods v0.9.1 and I have the following error:

```
TypeError: Cannot read property 'name' of undefined
    at NodePath.root.find.filter.replaceWith.p (/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:143:59)
    at NodePath.<anonymous> (/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:144:47)
    at __paths.forEach (/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:75:18)
    at Collection.replaceWith (/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:142:17)
    at Collection.typedMethod (/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:376:43)
    at shouldIdentifierToExpect (/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:131:126)
    at transformer (/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:302:18)
```

With a `console.log(calee)` in file `chai-should.js` line `139`:

```
Node {
  type: 'Identifier',
  start: 1929,
  end: 1935,
  loc:
   SourceLocation {
     start: Position { line: 71, column: 8 },
     end: Position { line: 71, column: 14 },
     lines: Lines {},
     indent: 8 },
  name: 'should',
  typeAnnotation: null }
```

Seems it's failing parsing this:

```js
should(foo).be.undefined();
```

I just had to manually migrate those lines (by commenting + manual replace).. 

```js
expect(foo).toBeUndefined();
```

Everything else seems working fine..

**Comment by skovhus** [comment]
Thanks for reporting this!

**Comment by skovhus** [comment]
@yvele I've haven't seen `should(foo).be...` syntax before. Usually `should` is added to all objects. So you do `foo.should.be`. 

Where have you seen that `should` can be used as a function? Do you have a link to documentation? : )

**Comment by yvele** [comment]
@skovhus `undefined` (and `null`) doesn't inherit `Object` and have the `should` getter, that's why we have to:

```js
should(foo).be.undefined();
```

Sources:
 - http://chaijs.com/guide/styles/#should-extras
 - http://stackoverflow.com/a/30596661/1480391
 - https://github.com/chaijs/chai/issues/90#issuecomment-7263749
 - http://stackoverflow.com/a/18102951/1480391

**Comment by skovhus** [comment]
Should.js is actually not chai should. They have different assertions it seems. chai should is required from the Chai packages, that is why imports of should is not removed.  

https://github.com/shouldjs/should.js/blob/master/Readme.md

**Comment by skovhus** [comment]
(Official) Should.js support released as 0.10.0. Let me know if it works for you. :)

**Comment by yvele** [comment]
@skovhus Hey.. I've being using 0.10.0 and I'm happy with it (nice should implementation)... but I still have problems with

```js
should(...).be.undefined();
should(...).be.null();
```

Here are the full error logs:

```
jest-codemods packages/*/test
? Which test library would you like to migrate from? Chai: Should/Expect BDD Syntax
Executing command: jscodeshift -t /Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js packages/package-pim/test packages/package-common/test packages/package-util/test
Processing 17 files...
Spawning 7 workers...
Sending 3 files to free worker...
Sending 3 files to free worker...
Sending 3 files to free worker...
Sending 3 files to free worker...
Sending 3 files to free worker...
Sending 2 files to free worker...
 ERR packages/package-common/test/identity.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at NodePath.root.find.filter.replaceWith.p (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:131:59)
    at NodePath.<anonymous> (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:144:47)
    at __paths.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:75:18)
    at Collection.replaceWith (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:142:17)
    at Collection.typedMethod (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:376:43)
    at shouldIdentifierToExpect (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:122:126)
    at transformer (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:300:18)
 ERR packages/package-util/test/string/truncate.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at NodePath.root.find.filter.replaceWith.p (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:131:59)
    at NodePath.<anonymous> (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:144:47)
    at __paths.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:75:18)
    at Collection.replaceWith (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:142:17)
    at Collection.typedMethod (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:376:43)
    at shouldIdentifierToExpect (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:122:126)
    at transformer (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:300:18)
 ERR packages/package-util/test/url/querystring/stringify.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at NodePath.root.find.filter.replaceWith.p (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:131:59)
    at NodePath.<anonymous> (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:144:47)
    at __paths.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:75:18)
    at Collection.replaceWith (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/collections/Node.js:142:17)
    at Collection.typedMethod (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/node_modules/jscodeshift/dist/Collection.js:376:43)
    at shouldIdentifierToExpect (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:122:126)
    at transformer (/Users/yves/.nvm/versions/node/v6.5.0/lib/node_modules/jest-codemods/dist/transformers/chai-should.js:300:18)
All done.
Results:
3 errors
0 unmodified
7 skipped
7 ok
Time elapsed: 3.653seconds
```

**Comment by skovhus** [comment]
Can you create a github issue? That would help me. Thanks for reporting!
