### ISSUE TITLE
Troubles converting from expect 1.x: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by erikras** [skovhus/jest-codemods#73]
I have been doing some potentially naughty extending of Expect 1.x, and I have been commenting them out as I go, with plans to fix them after the codemod goes though, but I'm stuck with this perplexing error.

Code is in the `jest` branch here: https://github.com/erikras/redux-form/tree/jest

```bash
$ jest-codemods --parser flow --dry
? Which test library would you like to migrate from? Expect@1.x (by mjackson)
? Should the tests be able to run in a browser? The tests should run on node.js (recommended)
? On which files or directory should the codemods be applied? src,test/**/*.js
Executing command: jscodeshift -t /usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js src --dry --parser flow
Processing 211 files...
Spawning 7 workers...
Running in dry mode, no files will be written!
Sending 31 files to free worker...
Sending 31 files to free worker...
Sending 31 files to free worker...
Sending 31 files to free worker...
Sending 31 files to free worker...
Sending 31 files to free worker...
Sending 25 files to free worker...
 ERR src/__tests__/createFieldArrayProps.spec.js Transformation error
TypeError: Cannot read property 'name' of undefined
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:250:63)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
    at expectTransformer (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:293:5)
 ERR src/__tests__/values.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/formValues.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/FieldArray.spec.js Transformation error
Error: Unknown matcher "toHaveText" (JEST_MATCHER_TO_MAX_ARGS)
    at balanceMatcherNodeArguments (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:78:19)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:162:9)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateMatchers (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:102:8)
    at expectTransformer (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:292:5)
 ERR src/__tests__/generateValidator.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/handleSubmit.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/Field.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/reduxForm.spec.js Transformation error
Error: Unknown matcher "toContainExactly" (JEST_MATCHER_TO_MAX_ARGS)
    at balanceMatcherNodeArguments (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:78:19)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:162:9)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateMatchers (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:102:8)
    at expectTransformer (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:292:5)
 ERR src/__tests__/Fields.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/Form.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/FormSection.spec.js Transformation error
Error: undefined does not match field "name": string of type Identifier
    at add (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
    at /usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
    at Array.forEach (native)
    at Function.value [as identifier] (/usr/local/lib/node_modules/jest-codemods/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
    at updateSpyProperty (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:252:152)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:288:13)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateSpies (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:285:12)
 ERR src/__tests__/actions.spec.js Transformation error
Error: Unknown matcher "toPass" (JEST_MATCHER_TO_MAX_ARGS)
    at balanceMatcherNodeArguments (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:78:19)
    at NodePath.ast.find.forEach.path (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:162:9)
    at __paths.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/jest-codemods/node_modules/jscodeshift/src/Collection.js:75:18)
    at updateMatchers (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:102:8)
    at expectTransformer (/usr/local/lib/node_modules/jest-codemods/dist/transformers/expect.js:292:5)
All done.
Results:
12 errors
171 unmodified
0 skipped
28 ok
Time elapsed: 7.359seconds
```

Any help would be appreciated.

**Comment by skovhus** [comment]
I have a few busy days, but let me look at this. I would love to help and make next migration easier for the next guy. 

: )

Thanks for reporting this!

**Comment by erikras** [comment]
I was going to say that any help would be appreciated, but I see I've already said that. 😆

**Comment by erikras** [comment]
FYI: The `toPass` error is related to [`expect-predicate`](https://github.com/erikras/expect-predicate).

**Comment by skovhus** [comment]
After investigating `redux-form` usage of `expect` I see several challenges for this codemod:
- chaining is used a lot (e.g. `expect(state).toExist().toBeAMap().toBeSize(1).toEqualMap`), which we currently not are handling... But we can make some of them work
- usage of `expect.extend` (which we at least should warn if people do)
- usage of https://github.com/erikras/expect-predicate (which I guess we can codemod our way out of)
- combined usage of expect and maybe jasmine (else I don't know where `toBeAMap` comes from...) See https://www.npmjs.com/package/jasmine-utils ... @erikras thoughts?
- where does `toBeSize` come from? This is not `expect`...

**Comment by erikras** [comment]
@skovhus You didn't look at [the branch I mentioned](https://github.com/erikras/redux-form/tree/jest). I've already manually done the "Easy" and "Harder" work, before I got down to the errors posted above.

Supporting chaining would be a _HUGE_ improvement to this lib, as that was a serious pain to fix.

I'm doing some crazy ninja js shit with "expectations" for both [plain](https://github.com/erikras/redux-form/blob/jest/src/structure/plain/expectations.js) and [immutable](https://github.com/erikras/redux-form/blob/jest/src/structure/immutable/expectations.js) data structures, using [`addExpectations`](https://github.com/erikras/redux-form/blob/jest/src/__tests__/addExpectations.js) to "decorate" `expect` to allow tests that will compare both ImmutableJS `Map`s and plain javascript objects the same way. Perhaps my recklessness is coming back to bite me...

**Comment by skovhus** [comment]
> @skovhus You didn't look at the branch I mentioned. I've already manually done the "Easy" and "Harder" work, before I got down to the errors posted above.

I did. But I wouldn't want you to do any manual fixes (although I few might be needed). Right now manual fixes where needed as we actually crashed. That has been fixed.

> Supporting chaining would be a HUGE improvement to this lib, as that was a serious pain to fix.

Agree. Hold tight. I'll use `redux-form` as an example for a more complex lib to migrate over. Previously I use a lot of mjacksons own libs like react-router and history. Not promising that there will be no manual steps, but the codemod here should get you 90%+ of the way. : )

**Comment by erikras** [comment]
Ah, apologies for misassumptions.

Should I sit back and await further updates on this issue?

**Comment by skovhus** [comment]
> Should I sit back and await further updates on this issue?

If you can wait a week with upgrading, then I would like to use the project as a case for making the codemod better. 🍷

**Comment by erikras** [comment]
Good deal. I did a release an hour ago, so I'm good to hold steady. I'd've liked to fit this jest migration into the release, but I'm good with waiting.

**Comment by skovhus** [comment]
jest-codemods@0.13.1 now can concert `redux-form` without crashing... Good start. 

But the issues mentioned above like chaining and custom matchers still needs more work from my side. : )

**Comment by skovhus** [comment]
Update: redux-form is now using Jest. 🍾 

https://github.com/erikras/redux-form/pull/3413
